// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

// //go:generate genny -in=$GOFILE -out=$GOFILE gen "String=BUILTINS,*MyType"

// https://github.com/cheekybits/genny
// Нужно просто вызвать в данной папке "go generate", в корне "go generate ./queue"
// Документация по генерации "go help generate"

package queue

// SomethingQueue is a queue of Somethings.
type StringQueue struct {
	items []string
}

func NewStringQueue() *StringQueue {
	return &StringQueue{items: make([]string, 0)}
}
func (q *StringQueue) Push(item string) {
	q.items = append(q.items, item)
}
func (q *StringQueue) Pop() string {
	item := q.items[0]
	q.items = q.items[1:]
	return item
}
